<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';import {api,clearToken,hasToken,saveToken} from './api'
type Obj=Record<string,any>;type View='home'|'questions'|'practice'|'community'|'ops'|'admin'
const view=ref<View>((location.hash.slice(1) as View)||'home'),loading=ref(false),error=ref(''),notice=ref(''),user=ref<Obj|null>(null),loginOpen=ref(!hasToken())
const questions=ref<Obj[]>([]),questionTotal=ref(0),keyword=ref(''),selected=ref<Obj|null>(null),categories=ref<Obj[]>([]),searchSource=ref(''),selectedCategory=ref<number|null>(null),selectedLabel=ref<number|null>(null),selectedType=ref('')
const practice=ref<Obj|null>(null),practiceId=ref<number|null>(null),answers=ref<Record<number,string>>({}),report=ref<Obj|null>(null),unfinished=ref<Obj[]>([])
const circles=ref<Obj[]>([]),posts=ref<Obj[]>([]),postDetail=ref<Obj|null>(null),comments=ref<Obj[]>([]),newPost=ref({circleId:1,title:'',content:''}),newComment=ref(''),selectedCircle=ref<number|null>(null),loadedReplies=ref<Record<number,Obj[]>>({}),replyDrafts=ref<Record<number,string>>({}),replyParents=ref<Record<number,number>>({})
const dashboard=ref<Obj|null>(null),admin=ref<Obj|null>(null),credentials=ref({username:'club-admin',password:'Club@123'}),authMode=ref<'login'|'register'>('login'),registerForm=ref({username:'',password:'',nickname:''})
const questionForm=ref({name:'',analysis:'',referenceAnswer:'',difficulty:2,score:1,type:'RADIO',status:'DRAFT',categoryIds:[2],labelIds:[1],options:[{code:'A',content:'',correct:true},{code:'B',content:'',correct:false}]}),wordForm=ref({word:'',type:'BLACK'})
const categoryForm=ref({name:'',parentId:null as number|null,sortNo:0,status:'ENABLED'}),labelForm=ref({name:'',categoryId:2,status:'ENABLED'})
const isAdmin=computed(()=>user.value?.role==='ADMIN')
const availableLabels=computed(()=>categories.value.find(c=>c.categoryId===selectedCategory.value)?.labels||[])
const flatCircles=computed(()=>circles.value.flatMap(c=>[c,...(c.children||[])]))
const typeLabels:Record<string,string>={RADIO:'单选题',MULTIPLE:'多选题',JUDGE:'判断题',BRIEF:'简答题'}
const stateLabels:Record<string,string>={UP:'正常',DOWN:'异常',DISABLED:'未启用',UNKNOWN:'未知',DRAFT:'草稿',PUBLISHED:'已发布',OFFLINE:'已下架',VISIBLE:'可见',HIDDEN_ADMIN:'管理员隐藏',ENABLED:'启用'}
const metricLabels:Record<string,string>={questions:'题目',categories:'分类',labels:'标签',posts:'帖子',comments:'评论',sensitiveWords:'敏感词'}
function typeName(value:string){return typeLabels[value]||value}
function stateName(value:string){return stateLabels[value]||value}
function sourceName(value:string){return value==='ELASTICSEARCH'?'Elasticsearch 全文索引':value==='MYSQL_LIMITED'?'MySQL 受限降级':'题库查询'}
function go(next:View){view.value=next;location.hash=next;selected.value=null;error.value='';loadView()}
async function run(action:()=>Promise<void>){loading.value=true;error.value='';notice.value='';try{await action()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{loading.value=false}}
async function login(){await run(async()=>{const data=await api<Obj>('/api/auth/login',{method:'POST',body:JSON.stringify(credentials.value)});saveToken(data.tokenValue);user.value=data.user;loginOpen.value=false;notice.value='登录成功';await loadView()})}
async function register(){await run(async()=>{await api('/api/auth/register',{method:'POST',body:JSON.stringify(registerForm.value)});credentials.value={username:registerForm.value.username,password:registerForm.value.password};authMode.value='login';await login()})}
async function logout(){await run(async()=>{await api('/api/auth/logout',{method:'POST'});clearToken();user.value=null;loginOpen.value=true})}
async function loadMe(){if(!hasToken())return;try{user.value=await api('/api/auth/me')}catch{clearToken()}}
async function loadCatalog(){if(categories.value.length)return;const roots=await api<Obj[]>('/api/catalog/categories');const groups=await Promise.all(roots.map(root=>api<Obj[]>(`/api/catalog/aggregate?parentId=${root.id}`)));categories.value=groups.flat()}
async function loadQuestions(search=false){await run(async()=>{await loadCatalog();const params=new URLSearchParams({page:'1',size:'20'});if(keyword.value)params.set('keyword',keyword.value);if(selectedCategory.value)params.set('categoryId',String(selectedCategory.value));if(selectedLabel.value)params.set('labelId',String(selectedLabel.value));if(selectedType.value)params.set('type',selectedType.value);if(search&&keyword.value){params.set('sort','relevance');const data=await api<Obj>(`/api/search?${params}`);questions.value=data.records;questionTotal.value=data.total;searchSource.value=data.source}else{params.set('status','PUBLISHED');const data=await api<Obj>(`/api/questions?${params}`);questions.value=data.records;questionTotal.value=data.total;searchSource.value='题库查询'}if(user.value)await Promise.all(questions.value.map(async q=>Object.assign(q,await api(`/api/questions/${q.id}/like`))))})}
function changeCategory(){selectedLabel.value=null;loadQuestions(Boolean(keyword.value))}
async function openQuestion(id:number){await run(async()=>{selected.value=await api(`/api/questions/${id}`)})}
async function startPractice(){if(!user.value){loginOpen.value=true;return}await run(async()=>{const data=await api<Obj>('/api/practices',{method:'POST',body:JSON.stringify({title:'Java 核心专项练习',count:5})});practiceId.value=data.id;practice.value=await api(`/api/practices/${data.id}`);report.value=null;go('practice')})}
async function saveAnswer(item:Obj){if(!practiceId.value)return;await api(`/api/practices/${practiceId.value}/answers`,{method:'PUT',body:JSON.stringify({questionId:item.questionId,answer:answers.value[item.questionId]||'',elapsedSeconds:60})});notice.value='进度已保存，可随时断点续答'}
async function submitPractice(){if(!practiceId.value)return;await run(async()=>{report.value=await api(`/api/practices/${practiceId.value}/submit`,{method:'POST',body:JSON.stringify({elapsedSeconds:120})});practice.value=null})}
async function loadPractice(){if(!user.value){unfinished.value=[];return}await run(async()=>{unfinished.value=await api('/api/practices/unfinished')})}
async function resumePractice(id:number){await run(async()=>{practiceId.value=id;practice.value=await api(`/api/practices/${id}`);answers.value={};for(const item of practice.value?.questions||[])answers.value[item.questionId]=item.answer||'';report.value=null})}
function selectAnswer(item:Obj,code:string,event:Event){const checked=(event.target as HTMLInputElement).checked;if(item.question.type==='MULTIPLE'){const selected=new Set((answers.value[item.questionId]||'').split(',').filter(Boolean));checked?selected.add(code):selected.delete(code);answers.value[item.questionId]=[...selected].sort().join(',')}else answers.value[item.questionId]=code}
async function loadCommunity(circleId:number|null=selectedCircle.value){await run(async()=>{if(!circles.value.length)circles.value=await api('/api/community/circles');selectedCircle.value=circleId;const suffix=circleId?`&circleId=${circleId}`:'';const data=await api<Obj>(`/api/community/posts?page=1&size=20${suffix}`);posts.value=data.records})}
async function chooseCircle(id:number|null){selectedCircle.value=id;if(id)newPost.value.circleId=id;await loadCommunity(id)}
async function openPost(id:number){await run(async()=>{postDetail.value=await api(`/api/community/posts/${id}`);const data=await api<Obj>(`/api/community/comments?bizType=POST&bizId=${id}&size=20`);comments.value=data.records;loadedReplies.value={};replyParents.value={}})}
async function loadReplies(rootId:number){const data=await api<Obj>(`/api/community/replies?rootId=${rootId}&page=1&size=20`);loadedReplies.value[rootId]=data.records}
async function publishReply(root:Obj){const content=replyDrafts.value[root.id];if(!content)return;await run(async()=>{const postId=postDetail.value?.id;await api('/api/community/comments',{method:'POST',body:JSON.stringify({bizType:'POST',bizId:postId,parentId:replyParents.value[root.id]||root.id,content})});replyDrafts.value[root.id]='';await openPost(postId);notice.value='回复已发布'})}
async function publishPost(){if(!user.value){loginOpen.value=true;return}await run(async()=>{await api('/api/community/posts',{method:'POST',body:JSON.stringify(newPost.value)});newPost.value={circleId:1,title:'',content:''};await loadCommunity();notice.value='帖子发布成功'})}
async function publishComment(){const postId=postDetail.value?.id;if(!postId)return;await run(async()=>{await api('/api/community/comments',{method:'POST',body:JSON.stringify({bizType:'POST',bizId:postId,content:newComment.value})});newComment.value='';await openPost(postId)})}
async function toggleLike(q:Obj){if(!user.value){loginOpen.value=true;return}await run(async()=>{const state=await api<Obj>(`/api/questions/${q.id}/like`,{method:'PUT',body:JSON.stringify({liked:!q.liked})});q.liked=state.liked;q.likeCount=state.count})}
async function loadOps(){await run(async()=>{dashboard.value=await api('/api/ops/dashboard')})}
async function loadAdmin(){if(!isAdmin.value)return;await run(async()=>{const qp=await api<Obj>('/api/questions?status=&page=1&size=50');admin.value={overview:await api('/api/admin/overview'),questions:qp.records,categories:await api('/api/admin/categories'),labels:await api('/api/admin/labels'),types:await api('/api/admin/question-types'),posts:await api('/api/admin/posts'),comments:await api('/api/admin/comments'),words:await api('/api/admin/sensitive-words')}})}
async function createQuestion(){await run(async()=>{await api('/api/admin/questions',{method:'POST',body:JSON.stringify(questionForm.value)});questionForm.value.name='';questionForm.value.analysis='';await loadAdmin();notice.value='题目已保存为草稿'})}
async function questionStatus(id:number,status:'publish'|'offline'){await run(async()=>{await api(`/api/admin/questions/${id}/${status}`,{method:'POST'});await loadAdmin()})}
async function moderate(target:string,id:number,status:string){await run(async()=>{await api(`/api/admin/${target}/${id}/status`,{method:'PUT',body:JSON.stringify({status})});await loadAdmin()})}
async function addWord(){await run(async()=>{await api('/api/admin/sensitive-words',{method:'POST',body:JSON.stringify(wordForm.value)});wordForm.value.word='';await loadAdmin();notice.value='词库已热更新，存量内容复检任务已创建'})}
async function addCategory(){await run(async()=>{await api('/api/admin/categories',{method:'POST',body:JSON.stringify(categoryForm.value)});categoryForm.value.name='';await loadAdmin()})}
async function addLabel(){await run(async()=>{await api('/api/admin/labels',{method:'POST',body:JSON.stringify(labelForm.value)});labelForm.value.name='';await loadAdmin()})}
async function loadView(){if(view.value==='questions')await loadQuestions();else if(view.value==='practice')await loadPractice();else if(view.value==='community')await loadCommunity();else if(view.value==='ops')await loadOps();else if(view.value==='admin')await loadAdmin()}
function safeHighlight(value:string){const escaped=(value||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');return escaped.replaceAll('&lt;mark&gt;','<mark>').replaceAll('&lt;/mark&gt;','</mark>')}
onMounted(async()=>{await loadMe();await loadView()})
</script>

<template>
<div class="shell">
  <header><button class="brand" @click="go('home')"><span class="brand-mark">C</span><span>面试刷题 Club<small>工程化实战平台</small></span></button><nav><button :class="{active:view==='questions'}" @click="go('questions')">题库</button><button :class="{active:view==='practice'}" @click="go('practice')">专项练习</button><button :class="{active:view==='community'}" @click="go('community')">社区</button><button :class="{active:view==='ops'}" @click="go('ops')">技术面板</button><button v-if="isAdmin" :class="{active:view==='admin'}" @click="go('admin')">管理后台</button></nav><div class="account"><span v-if="user">{{user.nickname}} · {{isAdmin?'管理员':'用户'}}</span><button class="outline" @click="user?logout():loginOpen=true">{{user?'退出':'登录'}}</button></div></header>
  <div v-if="loading" class="loading">正在加载真实业务数据…</div><div v-if="error" class="toast error">{{error}}</div><div v-if="notice" class="toast">{{notice}}</div>
  <main>
    <section v-if="view==='home'" class="hero"><div><p class="eyebrow">面试练习社区</p><h1>把每一次练习，<br><em>沉淀成可验证的成长。</em></h1><p class="lead">从题库筛选、专项练习、断点续答到自动判分与社区讨论，所有操作都进入真实业务链路。</p><div class="actions"><button class="primary" @click="go('questions')">开始刷题</button><button class="outline" @click="go('ops')">查看工程面板</button></div><div class="proof"><span>✓ 四类题型策略</span><span>✓ 实时进度保存</span><span>✓ 搜索高亮与降级</span></div></div><aside><div class="metric"><b>10,000+</b><span>题库容量设计</span></div><div class="metric"><b>36 毫秒</b><span>聚合接口实测口径</span></div><div class="metric"><b>最终一致</b><span>消息 + 补偿闭环</span></div></aside></section>
    <section v-if="view==='questions'" class="page"><div class="title"><div><p class="eyebrow">题库</p><h2>精选题库</h2><p>按名称、分类、标签与题型定位知识盲区。</p></div><button class="primary" @click="startPractice">生成专项练习</button></div><div class="search"><input v-model="keyword" placeholder="搜索题目名称或解析"><select v-model="selectedCategory" @change="changeCategory"><option :value="null">全部分类</option><option v-for="c in categories" :key="c.categoryId" :value="c.categoryId">{{c.categoryName}}</option></select><select v-model="selectedLabel" @change="loadQuestions(Boolean(keyword))"><option :value="null">全部标签</option><option v-for="l in availableLabels" :key="l.id" :value="l.id">{{l.name}}</option></select><select v-model="selectedType" @change="loadQuestions(Boolean(keyword))"><option value="">全部题型</option><option value="RADIO">单选题</option><option value="MULTIPLE">多选题</option><option value="JUDGE">判断题</option><option value="BRIEF">简答题</option></select><button @click="loadQuestions(true)">全文搜索</button><button class="ghost" @click="keyword='';selectedCategory=null;selectedLabel=null;selectedType='';loadQuestions()">重置</button></div><p class="hint">共 {{questionTotal}} 道题 · 数据源：{{sourceName(searchSource)}}</p><div v-if="!questions.length" class="empty">暂无符合条件的题目</div><div class="question-grid"><article v-for="q in questions" :key="q.id" @click="openQuestion(q.id)"><span class="badge">{{typeName(q.type||q.question_type)}}</span><h3 v-html="safeHighlight(q.highlightName||q.name)"></h3><footer><span>难度 {{q.difficulty}} / 5</span><button class="like" @click.stop="toggleLike(q)">{{q.liked?'已赞':'点赞'}} {{q.likeCount||''}}</button></footer></article></div></section>
    <section v-if="view==='practice'" class="page"><div class="title"><div><p class="eyebrow">专项训练</p><h2>专项练习</h2><p>答案实时保存，刷新页面后可从未交卷记录继续。</p></div><button v-if="!practice&&!report" class="primary" @click="startPractice">生成 5 题练习</button></div><div v-if="!practice&&!report&&unfinished.length" class="unfinished"><h3>继续未完成练习</h3><button v-for="item in unfinished" :key="item.id" class="outline" @click="resumePractice(item.id)">{{item.title}} · 已用时 {{item.elapsedSeconds}} 秒</button></div><div v-if="practice" class="practice"><article v-for="(item,index) in practice.questions" :key="item.questionId"><span>第 {{Number(index)+1}} 题</span><h3>{{item.question.name}}</h3><label v-for="op in item.question.options" :key="op.code"><input :type="item.question.type==='MULTIPLE'?'checkbox':'radio'" :name="`question-${item.questionId}`" :checked="(answers[item.questionId]||'').split(',').includes(op.code)" @change="selectAnswer(item,op.code,$event)"> {{op.code}}. {{op.content}}</label><input v-if="!item.question.options?.length" v-model="answers[item.questionId]" placeholder="输入你的答案"><button class="ghost" @click="saveAnswer(item)">保存本题进度</button></article><button class="primary" @click="submitPractice">交卷并生成报告</button></div><div v-else-if="report" class="report"><div class="score"><b>{{report.correctRate}}%</b><span>正确率</span></div><h3>{{report.title}}</h3><p>答对 {{report.correct_count}} / {{report.total_count}}，用时 {{report.elapsed_seconds}} 秒。</p><div v-for="item in report.labelStats" :key="item.labelId" class="bar"><span>{{item.labelName}}</span><b>{{item.correct}} / {{item.total}}</b></div></div><div v-else-if="!unfinished.length" class="empty">尚未开始练习，登录后即可生成专项题单。</div></section>
    <section v-if="view==='community'" class="page"><div class="title"><div><p class="eyebrow">学习社区</p><h2>学习圈子</h2><p>分享思路、追问难点，回复按需加载。</p></div></div><div class="community"><aside><h3>圈子</h3><button :class="{active:selectedCircle===null}" @click="chooseCircle(null)">全部讨论</button><button v-for="c in flatCircles" :key="c.id" :class="{active:selectedCircle===c.id}" @click="chooseCircle(c.id)">{{c.name}}</button><h3>发布讨论</h3><input v-model="newPost.title" placeholder="帖子标题"><textarea v-model="newPost.content" placeholder="写下你的思考"></textarea><button class="primary" @click="publishPost">发布</button></aside><div><article v-for="p in posts" :key="p.id" class="post" @click="openPost(p.id)"><h3>{{p.title}}</h3><p>{{p.content}}</p><footer>{{p.commentCount||0}} 条评论 · {{p.likeCount||0}} 个赞</footer></article><div v-if="!posts.length" class="empty">这个圈子还没有讨论</div></div></div></section>
    <section v-if="view==='ops'" class="page"><div class="title"><div><p class="eyebrow">工程可观测</p><h2>工程运行面板</h2><p>全部指标来自应用、数据库、缓存和任务的真实接口。</p></div><button class="outline" @click="loadOps">刷新</button></div><div v-if="dashboard" class="dash"><article><span>服务状态</span><b>{{stateName(dashboard.service.status)}}</b><small>{{dashboard.service.questionCount}} 道题 · {{dashboard.service.userCount}} 位用户</small></article><article><span>请求量 / P95</span><b>{{dashboard.requests.count}} / {{dashboard.requests.p95Millis}} 毫秒</b><small>平均 {{dashboard.requests.averageMillis}} 毫秒 · 错误率 {{dashboard.requests.errorRate}}%</small></article><article><span>数据库连接</span><b>{{dashboard.database.active}} / {{dashboard.database.max}}</b><small>等待 {{dashboard.database.waiting}} · {{stateName(dashboard.database.status)}}</small></article><article><span>Redis / 待处理点赞</span><b>{{stateName(dashboard.redis.status)}} / {{dashboard.message.likePending}}</b><small>最老记录 {{dashboard.message.oldestAgeSeconds}} 秒 · 阈值 {{dashboard.message.countThreshold}} 条或 {{dashboard.message.ageThresholdSeconds}} 秒</small></article><article><span>Caffeine 命中率</span><b>{{dashboard.cache.hitRate}}%</b><small>{{dashboard.cache.requestCount}} 次请求 · {{dashboard.cache.pendingInvalidations}} 条失效任务</small></article><article><span>Elasticsearch</span><b>{{stateName(dashboard.search.status)}}</b><small>{{dashboard.search.enabled?'已启用搜索集群':'演示环境未启用，使用 MySQL 受限降级'}}</small></article></div></section>
    <section v-if="view==='admin'" class="page"><div class="title"><div><p class="eyebrow">管理控制台</p><h2>内容管理</h2><p>题目、分类、标签、题型、帖子、评论与敏感词统一维护。</p></div></div><div v-if="!isAdmin" class="empty">仅管理员可访问</div><template v-else-if="admin"><div class="stats"><span v-for="(value,key) in admin.overview" :key="key"><b>{{value}}</b>{{metricLabels[String(key)]||key}}</span></div><div class="admin-panels"><article><h3>新建题目</h3><input v-model="questionForm.name" placeholder="题目名称"><textarea v-model="questionForm.analysis" placeholder="题目解析"></textarea><div v-if="questionForm.type!=='BRIEF'" class="inline"><input v-model="questionForm.options[0].content" placeholder="正确选项 A"><input v-model="questionForm.options[1].content" placeholder="错误选项 B"></div><input v-else v-model="questionForm.referenceAnswer" placeholder="简答题参考答案"><div class="inline"><select v-model="questionForm.type"><option v-for="t in admin.types" :key="t.code" :value="t.code">{{t.name}}</option></select><button class="primary" @click="createQuestion">保存草稿</button></div></article><article><h3>敏感词热更新</h3><input v-model="wordForm.word" placeholder="输入词语"><div class="inline"><select v-model="wordForm.type"><option value="BLACK">黑名单</option><option value="WHITE">白名单</option></select><button class="primary" @click="addWord">加入词库</button></div><small>更新后自动创建存量内容复检任务。</small></article></div><div class="admin-panels"><article><h3>新增分类</h3><input v-model="categoryForm.name" placeholder="分类名称"><button class="primary" @click="addCategory">保存分类</button></article><article><h3>新增标签</h3><input v-model="labelForm.name" placeholder="标签名称"><button class="primary" @click="addLabel">保存标签</button></article></div><h3>题目维护</h3><div class="table"><div v-for="q in admin.questions" :key="q.id"><span>{{q.name}}</span><b>{{typeName(q.type)}} · {{stateName(q.status)}}</b><button @click="questionStatus(q.id,'publish')">发布</button><button @click="questionStatus(q.id,'offline')">下架</button></div></div><h3>社区审核</h3><div class="table"><div v-for="p in admin.posts" :key="p.id"><span>{{p.title}}</span><b>{{stateName(p.status)}}</b><button @click="moderate('post',p.id,p.status==='VISIBLE'?'HIDDEN_ADMIN':'VISIBLE')">{{p.status==='VISIBLE'?'隐藏':'恢复'}}</button></div><div v-for="c in admin.comments" :key="`comment-${c.id}`"><span>评论：{{c.content}}</span><b>{{stateName(c.status)}}</b><button @click="moderate('comment',c.id,c.status==='VISIBLE'?'HIDDEN_ADMIN':'VISIBLE')">{{c.status==='VISIBLE'?'隐藏':'恢复'}}</button></div></div><div class="admin-grid"><article><h3>分类与标签</h3><p>{{admin.categories.length}} 个分类 · {{admin.labels.length}} 个标签</p></article><article><h3>题型</h3><p>{{admin.types.map((t:Obj)=>t.name).join('、')}}</p></article><article><h3>敏感词库</h3><p>{{admin.words.length}} 条规则，支持黑白名单与热更新复检</p></article></div></template></section>
  </main>
  <div v-if="selected" class="modal" @click.self="selected=null"><div class="dialog"><button class="close" @click="selected=null">×</button><span class="badge">{{typeName(selected.type)}}</span><h2>{{selected.name}}</h2><div v-for="op in selected.options" :key="op.code" class="option">{{op.code}}. {{op.content}}</div><h3>题目解析</h3><p>{{selected.analysis||'登录后查看完整解析。'}}</p></div></div>
  <div v-if="postDetail" class="modal" @click.self="postDetail=null"><div class="dialog"><button class="close" @click="postDetail=null">×</button><h2>{{postDetail.title}}</h2><p>{{postDetail.content}}</p><h3>评论</h3><div v-if="!comments.length" class="empty small">暂无评论</div><div v-for="c in comments" :key="c.id" class="comment"><b>{{c.nickname||'学习者'}}</b><p>{{c.content}}</p><div v-for="r in (loadedReplies[c.id]||c.replies||[])" :key="r.id" class="reply"><b>{{r.nickname}}<span v-if="r.toNickname"> 回复 {{r.toNickname}}</span></b>：{{r.content}} <button class="ghost" @click="replyParents[c.id]=r.id">回复</button></div><button v-if="c.replyTotal>(loadedReplies[c.id]||c.replies||[]).length" class="ghost" @click="loadReplies(c.id)">加载全部 {{c.replyTotal}} 条回复</button><div class="inline"><input v-model="replyDrafts[c.id]" :placeholder="replyParents[c.id]?'回复指定用户':'回复这条评论'"><button @click="publishReply(c)">回复</button></div></div><textarea v-model="newComment" placeholder="写下一级评论"></textarea><button class="primary" @click="publishComment">发表评论</button></div></div>
  <div v-if="loginOpen" class="modal" @click.self="loginOpen=false"><form class="dialog login" @submit.prevent="authMode==='login'?login():register()"><button class="close" type="button" aria-label="关闭登录窗口" @click="loginOpen=false">×</button><span class="brand-mark">C</span><h2>{{authMode==='login'?'登录面试刷题 Club':'注册学习账号'}}</h2><p>{{authMode==='login'?'本地演示管理员账号已预填。':'注册后将自动登录。'}}</p><template v-if="authMode==='login'"><label>用户名<input v-model="credentials.username" autocomplete="username"></label><label>密码<input v-model="credentials.password" type="password" autocomplete="current-password"></label></template><template v-else><label>用户名<input v-model="registerForm.username" autocomplete="username" placeholder="4～32 位字母、数字或下划线"></label><label>昵称<input v-model="registerForm.nickname" placeholder="你的中文昵称"></label><label>密码<input v-model="registerForm.password" type="password" autocomplete="new-password" placeholder="至少 8 位"></label></template><button class="primary" type="submit">{{authMode==='login'?'登录':'注册并登录'}}</button><button class="ghost switch" type="button" @click="authMode=authMode==='login'?'register':'login'">{{authMode==='login'?'没有账号？立即注册':'已有账号？返回登录'}}</button><small v-if="authMode==='login'">演示账号：club-admin / Club@123（仅限本地开发环境）</small></form></div>
</div>
</template>
