package com.dyh.club.platform.admin;

import com.dyh.club.platform.common.BizException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Service
public class AdminService {
    private final JdbcTemplate jdbc;public AdminService(JdbcTemplate jdbc){this.jdbc=jdbc;}
    public Map<String,Object> overview(){return map("questions",count("club_question"),"categories",count("club_category"),"labels",count("club_label"),"posts",count("club_post"),"comments",count("club_comment"),"sensitiveWords",count("club_sensitive_word"));}
    public List<Map<String,Object>> categories(){return jdbc.queryForList("SELECT id,parent_id,name,sort_no,status,updated_at FROM club_category ORDER BY COALESCE(parent_id,0),sort_no,id");}
    public List<Map<String,Object>> labels(){return jdbc.queryForList("SELECT l.id,l.category_id,l.name,l.status,l.updated_at,c.name AS category_name FROM club_label l JOIN club_category c ON c.id=l.category_id ORDER BY l.id");}
    public List<Map<String,Object>> types(){List<Map<String,Object>>r=new ArrayList<>();r.add(map("code","RADIO","name","单选题"));r.add(map("code","MULTIPLE","name","多选题"));r.add(map("code","JUDGE","name","判断题"));r.add(map("code","BRIEF","name","简答题"));return r;}
    public List<Map<String,Object>> posts(){return jdbc.queryForList("SELECT p.id,p.title,p.status,p.comment_count,p.like_count,p.created_at,u.nickname AS author FROM club_post p JOIN club_user u ON u.id=p.author_id ORDER BY p.id DESC LIMIT 100");}
    public List<Map<String,Object>> comments(){return jdbc.queryForList("SELECT c.id,c.biz_type,c.biz_id,c.parent_id,c.content,c.status,c.audit_reason,c.created_at,u.nickname AS author FROM club_comment c JOIN club_user u ON u.id=c.author_id ORDER BY c.id DESC LIMIT 100");}
    @Transactional public long saveCategory(Long id,Long parentId,String name,Integer sortNo,String status){valid(name);if(id==null){KeyHolder key=new GeneratedKeyHolder();jdbc.update(c->{java.sql.PreparedStatement p=c.prepareStatement("INSERT INTO club_category(parent_id,name,sort_no,status) VALUES(?,?,?,?)",new String[]{"id"});p.setObject(1,parentId);p.setString(2,name.trim());p.setInt(3,sortNo==null?0:sortNo);p.setString(4,state(status));return p;},key);return Objects.requireNonNull(key.getKey()).longValue();}jdbc.update("UPDATE club_category SET parent_id=?,name=?,sort_no=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",parentId,name.trim(),sortNo==null?0:sortNo,state(status),id);return id;}
    @Transactional public long saveLabel(Long id,long categoryId,String name,String status){valid(name);if(id==null){KeyHolder key=new GeneratedKeyHolder();jdbc.update(c->{java.sql.PreparedStatement p=c.prepareStatement("INSERT INTO club_label(category_id,name,status) VALUES(?,?,?)",new String[]{"id"});p.setLong(1,categoryId);p.setString(2,name.trim());p.setString(3,state(status));return p;},key);return Objects.requireNonNull(key.getKey()).longValue();}jdbc.update("UPDATE club_label SET category_id=?,name=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",categoryId,name.trim(),state(status),id);return id;}
    @Transactional public void moderate(String target,long id,String status){if(!Arrays.asList("VISIBLE","HIDDEN_ADMIN").contains(status))throw BizException.badRequest("状态值不合法");if("post".equals(target)){if(jdbc.update("UPDATE club_post SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",status,id)==0)throw BizException.notFound("内容不存在");return;}if(!"comment".equals(target))throw BizException.badRequest("不支持的管理对象");Map<String,Object> old;try{old=jdbc.queryForMap("SELECT biz_type,biz_id,status FROM club_comment WHERE id=?",id);}catch(org.springframework.dao.EmptyResultDataAccessException e){throw BizException.notFound("内容不存在");}String before=String.valueOf(old.get("status"));if(before.equals(status))return;jdbc.update("UPDATE club_comment SET status=?,audit_reason=? WHERE id=?",status,"HIDDEN_ADMIN".equals(status)?"管理员隐藏":null,id);if("POST".equals(old.get("biz_type"))){if("VISIBLE".equals(before)&&"HIDDEN_ADMIN".equals(status))jdbc.update("UPDATE club_post SET comment_count=CASE WHEN comment_count>0 THEN comment_count-1 ELSE 0 END WHERE id=?",old.get("biz_id"));else if("HIDDEN_ADMIN".equals(before)&&"VISIBLE".equals(status))jdbc.update("UPDATE club_post SET comment_count=comment_count+1 WHERE id=?",old.get("biz_id"));}}
    private long count(String table){Number n=jdbc.queryForObject("SELECT COUNT(*) FROM "+table,Number.class);return n==null?0:n.longValue();}private void valid(String s){if(s==null||s.trim().isEmpty())throw BizException.badRequest("名称不能为空");}private String state(String s){return "DISABLED".equals(s)?"DISABLED":"ENABLED";}private static Map<String,Object>map(Object...v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put(String.valueOf(v[i]),v[i+1]);return m;}
}
